import type { Metadata } from "next";
import { fontCabin, fontMono, fontOutfit } from "@/lib/fonts";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontOutfit.variable} ${fontCabin.variable} ${fontMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
